baseurl = "/netfarjoX"
languageCode = 'en-us'
title = 'Netfarjo Website'
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Netfarjo"
    copyright = ""
 

    [languages.en.params.logo]
      logoText = "Netfarjo"
      logoHomeLink = "/netfarjoX"
      subtitle = "A simple theme for Hugo"
      keywords = ""
      minuteReadingTime = "min read"
      menuMore = "Show more"
      writtenBy = "Written by"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      dateFormatSingle = "2006-01-02"
      dateFormatList = "2006-01-02"

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
